/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import classes.Categoria;
import fachada.Fachada;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lipe
 */
public class AlterarCategoriasAgencia extends javax.swing.JFrame {

    Fachada fachada = new Fachada();
    int[] codigo;
    int cod;

    /**
     * Creates new form AlterarCategoriasAgencia
     */
    public AlterarCategoriasAgencia(int cod) {
        initComponents();
        this.cod = cod;
        ArrayList<Categoria> categorias = new ArrayList<>();
        DefaultTableModel tabela = new DefaultTableModel();
        try {
            categorias = fachada.listarCatAg(cod);
            tabela.setColumnIdentifiers(new String[]{"Codigo", "Nome"});
            for (int i = 0; i < categorias.size(); i++) {
                Categoria categoria = new Categoria();
                categoria = fachada.procurarCat(categorias.get(i).getCat_cod());
                tabela.addRow(new Object[]{categorias.get(i).getCat_cod(), categoria.getTipo()});
            }
            jTable1.setModel(tabela);
            categorias = new ArrayList<>();
            categorias = fachada.listarCat();
            codigo = new int[categorias.size()];
            for (int i = 0; i < categorias.size(); i++) {
                jComboBox1.addItem(categorias.get(i).getTipo());
                codigo[i] = categorias.get(i).getCat_cod();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    private AlterarCategoriasAgencia() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Alterar Categoria da Agência");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            fachada.cadastrarCategoriaAgencia(cod, codigo[jComboBox1.getSelectedIndex()]);
            JOptionPane.showMessageDialog(rootPane, "Categoria cadastrada com sucesso");
            ArrayList<Categoria> categorias = new ArrayList<>();
            DefaultTableModel tabela = new DefaultTableModel();

            categorias = fachada.listarCatAg(cod);
            tabela.setColumnIdentifiers(new String[]{"Codigo", "Nome"});
            for (int i = 0; i < categorias.size(); i++) {
                Categoria categoria = new Categoria();
                categoria = fachada.procurarCat(categorias.get(i).getCat_cod());
                tabela.addRow(new Object[]{categorias.get(i).getCat_cod(), categoria.getTipo()});
            }
            jTable1.setModel(tabela);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int selectedRow = jTable1.getSelectedRow();
            int val = jComboBox1.getSelectedIndex();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(rootPane, "Selecione um item na lista");
            } else {
                int codigoantigo = (Integer) jTable1.getValueAt(selectedRow, 0);
                fachada.alterarCategoriaAgencia(cod, codigoantigo, codigo[val]);
                JOptionPane.showMessageDialog(rootPane, "Cadastro Alterado com Sucesso");
                ArrayList<Categoria> categorias = new ArrayList<>();
                DefaultTableModel tabela = new DefaultTableModel();
                categorias = fachada.listarCatAg(cod);
                tabela.setColumnIdentifiers(new String[]{"Codigo", "Nome"});
                for (int i = 0; i < categorias.size(); i++) {
                    Categoria categoria = new Categoria();
                    categoria = fachada.procurarCat(categorias.get(i).getCat_cod());
                    tabela.addRow(new Object[]{categorias.get(i).getCat_cod(), categoria.getTipo()});
                }
                jTable1.setModel(tabela);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int selectedRow = jTable1.getSelectedRow();
            int val = jComboBox1.getSelectedIndex();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(rootPane, "Selecione um item na lista");
            } else {
                int codigoAntigo = (Integer) jTable1.getValueAt(selectedRow, 0);
                fachada.removerCategoriaAgencia(cod, codigoAntigo);
                JOptionPane.showMessageDialog(rootPane, "Cadastro removido com Sucesso");
                ArrayList<Categoria> categorias = new ArrayList<>();
                DefaultTableModel tabela = new DefaultTableModel();
                categorias = fachada.listarCatAg(cod);
                tabela.setColumnIdentifiers(new String[]{"Codigo", "Nome"});
                for (int i = 0; i < categorias.size(); i++) {
                    Categoria categoria = new Categoria();
                    categoria = fachada.procurarCat(categorias.get(i).getCat_cod());
                    tabela.addRow(new Object[]{categorias.get(i).getCat_cod(), categoria.getTipo()});
                }
                jTable1.setModel(tabela);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriasAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriasAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriasAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarCategoriasAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarCategoriasAgencia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
